import * as THREE from 'three';

export const CONFIG = {
  gridSize: 13,
  tile: 2.2,
  laneWidth: 1.22,
  defaultLaneCount: 1,
  maxLaneCount: 3,
  trackHeight: 0.18,
  railWidth: 0.05,
  railHeight: 0.25,
  railBaseOffset: 0.18,
  loopHeight: 4.2,
  loopEntryPortion: 0.01,
  loopExitPortion: 0.99,
  loopDepth: 5.45,
  loopStraightInset: 0.12,
  loopPathSamples: 72,
  loopMirrorLateral: true,
  carScale: 0.40,
  carVisualYOffset: -0.1,
  defaultCarCount: 1,
  maxCarCount: 10,
  physics: {
    startSpeed: 7.5,
    motorAccel: 18.0,
    minMotorSpeed: 1.8,
    drag: 0.18,
    maxSpeed: 21.0,
    weight: 0.8,
    uphillLoss: 3.4,
    downhillBoost: 2.2,
    minClimbSpeed: 1.65,
    climbStallDropDelay: 1.35,
    loopStallFallSurfaceUp: 0.15,
    climbRollbackAccel: 2.6,
    curveSafeSpeed: 5.8,
    curvePressure: 0.62,
    curveRailLoss: 0.32,
    stabilityRecover: 0.42,
    derailPressure: 2.4,
    stallSpeed: 0.12,
    fixedStep: 1 / 60,
    guideStrength: 12.5,
    centeringStrength: 5.8,
    maxCenterOffset: 0.42,
    laneCollisionWindow: 8,
    lateralFriction: 0.58,
    tireWander: 0.42,
    carRadius: 0.135,
    carCollisionHalfWidth: 0.13,
    carCollisionHalfLength: 0.11,
    carCollisionSkin: 0.015,
    laneClearance: 0.025,
    railRestitution: 0.18,
    railFriction: 0.985,
    lookAhead: 0.38,
    cornerSamples: 20,
    flightGravity: 7.8,
    flightAirDamping: 0.995,
    flightGroundDamping: 0.42,
    flightGroundClearance: 0.12,
    invertedGroundClearance: 0.2,
    rejoinHeightTolerance: 0.28,
    highToLowRejoinMinFlightTime: 0.32,
    highToLowRejoinMaxUpVelocity: -0.15,
    flightUprightThreshold: 0.38,
    derailedLandingSurfaceUp: 0.35,
    flightRejoinSpeed: 2.2,
    derailCollisionRadius: 0.24,
    derailRailBounce: 0.72,
    derailCarBounce: 0.68,
    offTrackFlipHits: 3,
    offTrackHitCooldown: 0.22,
    forcedFlipDuration: 0.38,
    offTrackCruiseSpeed: 2.4,
    offTrackDespawnDistance: 18,
    wreckFriction: 0.9,
    wreckStopSpeed: 0.28,
  },
  colors: {
    sky: 0xf4efd2,
    floor: 0xf4efd2,
    floorAlt: 0xeee7c4,
    grid: 0x6f7650,
    table: 0xeee7c4,
    track: 0xf4efd2,
    rail: 0xcccccc,
    railEdge: 0xffffff,
    accent: 0xf4bf3a,
    start: 0x1f8f63,
    crossover: 0xf4efd2,
    previewOk: 0x2f68bf,
    previewBad: 0xc94141,
    selected: 0x5f8dd3,
    cars: [0xe43d30, 0x2f68bf, 0x1f8f63, 0xf4bf3a],
  },
};

export const STORAGE_KEY = 'mini4wd.track.v1';

export const PIECES = {
  straight: { label: '直線', color: CONFIG.colors.track },
  curveL: { label: '左彎', color: CONFIG.colors.track },
  curveR: { label: '右彎', color: CONFIG.colors.track },
  crossover: { label: '交叉轉線', color: CONFIG.colors.track },
  wave: { label: '波浪道', color: CONFIG.colors.track },
  loop: { label: '垂直環', color: CONFIG.colors.track },
  start: { label: '起點', color: CONFIG.colors.track },
};

export const DIRS = [
  new THREE.Vector2(0, -1),
  new THREE.Vector2(1, 0),
  new THREE.Vector2(0, 1),
  new THREE.Vector2(-1, 0),
];
