import * as THREE from 'three';

export const CONFIG = {
  gridSize: 13,
  tile: 2.2,
  laneWidth: 1.22,
  defaultLaneCount: 1,
  maxLaneCount: 3,
  trackHeight: 0.18,
  railWidth: 0.05,
  railHeight: 0.25,
  railBaseOffset: 0.18,
  carScale: 0.54,
  carVisualYOffset: -0.1,
  defaultCarCount: 1,
  maxCarCount: 4,
  physics: {
    startSpeed: 3.8,
    motorAccel: 4.1,
    minMotorSpeed: 1.8,
    drag: 0.18,
    maxSpeed: 12.2,
    uphillLoss: 3.4,
    downhillBoost: 2.2,
    minClimbSpeed: 1.65,
    curveSafeSpeed: 4.65,
    curvePressure: 0.62,
    curveRailLoss: 1.1,
    stabilityRecover: 0.42,
    derailPressure: 2.4,
    stallSpeed: 0.12,
    fixedStep: 1 / 60,
    guideStrength: 12.5,
    centeringStrength: 5.8,
    maxCenterOffset: 0.42,
    lateralFriction: 0.9,
    tireWander: 0.42,
    carRadius: 0.135,
    laneClearance: 0.055,
    railRestitution: 0.18,
    railFriction: 0.94,
    lookAhead: 0.38,
    cornerSamples: 20,
  },
  colors: {
    sky: 0xf4efd2,
    floor: 0xf4efd2,
    floorAlt: 0xeee7c4,
    grid: 0x6f7650,
    table: 0xc9bd83,
    track: 0xf4efd2,
    rail: 0xcccccc,
    accent: 0xf4bf3a,
    start: 0x1f8f63,
    crossover: 0xf4efd2,
    previewOk: 0x2f68bf,
    previewBad: 0xc94141,
    selected: 0x5f8dd3,
    cars: [0xe43d30, 0x2f68bf, 0x1f8f63, 0xf4bf3a],
  },
};

export const STORAGE_KEY = 'mini4wd.track.v1';

export const PIECES = {
  straight: { label: '直線', color: CONFIG.colors.track },
  curveL: { label: '左彎', color: CONFIG.colors.track },
  curveR: { label: '右彎', color: CONFIG.colors.track },
  crossover: { label: '交叉轉線', color: CONFIG.colors.track },
  wave: { label: '波浪道', color: CONFIG.colors.track },
  start: { label: '起點', color: CONFIG.colors.track },
};

export const DIRS = [
  new THREE.Vector2(0, -1),
  new THREE.Vector2(1, 0),
  new THREE.Vector2(0, 1),
  new THREE.Vector2(-1, 0),
];
